// <auto-generated />
namespace ScribesF4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatetest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetest));
        
        string IMigrationMetadata.Id
        {
            get { return "201601310601343_update test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
